#name: Deploy to cPanel
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Deploy to cPanel
#        run: |
#          ssh vychevs4@test-market.ru 'ls'
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup ssh key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"

      - name: Sync files
      - run: |
          rsync -e \
          "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" \
          --archive --compress --delete \
          ./src/ vychevs4@test-market.ru:/home/vychevs4/public_html
