name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to cPanel
        run: |
          ssh vychevs4@test-market.ru 'ls'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

#          ssh username@yourdomain.com 'cd /path/to/your/repository && git pull'
