#name: Deploy to cPanel
#
#on:
#  pull_request:
#    types: [closed]
#    branches:
#      - master
#
#jobs:
#  deploy:
#    if: ${{ github.event.pull_request.merged == true }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      # Setup ssh key
#      - run: |
#          set -eu
#          mkdir "$HOME/.ssh"
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/key"
#          chmod 600 "$HOME/.ssh/key"
#
#      # Sync files
#      - run: |
#          rsync -v -e \
#          "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" \
#          --archive --compress --delete \
#          --exclude 'db.php' \
#          --exclude 'env.php' \
#          --exclude 'admin/env.php' \
#          --exclude 'image/cache/' \
#          --exclude 'system/storage/backup/' \
#          --exclude 'system/storage/cache/' \
#          --exclude 'system/storage/download/' \
#          --exclude 'system/storage/logs/' \
#          --exclude 'system/storage/session/' \
#          --exclude 'system/storage/upload/' \
#          ./src/ vychevs4@test-market.ru:/home/vychevs4/public_html
